# This Config is just for etherpad service

version: "3.3"

services:
  etherpad-lite:
    build:
      context: .
    env_file: docker-compose.env
    image: tailchat-etherpad
    environment:
      DB_TYPE: mongodb
      DB_URL: mongodb://mongo:27017/tailchat_ep
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ep.rule=PathPrefix(`/ep/`)"
      - "traefik.http.services.ep.loadbalancer.server.port=9001"
      - "traefik.http.middlewares.ep-prefix.stripprefix.prefixes=/ep/"
      - "traefik.http.routers.ep.middlewares=ep-prefix"
    networks:
      - tailchat

networks:
  tailchat:
    external:
      name: tailchat-internal
